---
- name: leapp_missing_efibootmgr | Install efibootmgr package - required on EFI systems
  block:
    - name: leapp_missing_efibootmgr | Install efibootmgr package
      ansible.builtin.dnf:
        name: efibootmgr
        state: present
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 8
      # While this will complain on current linters as yum is deprecated, running against RHEL 7
      # does require an older version of Ansible that still has ansible.builtin.yum
    - name: leapp_missing_efibootmgr | Install efibootmgr package # noqa: fqcn[action-core]
      ansible.builtin.yum:
        name: efibootmgr
        state: present
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7
...
